Repository acm-ucr/witl-website, pull requests merged in 2024-07, with the labels that each got.

#20 Implemented navbar
  public/images/WITL-logo.webp
  src/app/layout.js
  src/app/resources/page.js
  src/components/Navigation.jsx
  src/data/Nav.js
Labels: changes requested

#38 justin-h-im/about page
  src/app/about/page.js
  src/components/about.jsx
  src/components/about/about.jsx
  tailwind.config.js
Labels: ready for review, changes requested

#39 cathy/pageNotFoundAdjective
  src/components/NotFound.jsx
Labels: changes requested

#37 added 404
  src/components/NotFound.jsx
Labels: changes requested

#41 Added footer component and data file for icons
  public/assets/bookmark.svg
  public/assets/discord.svg
  public/assets/email.svg
  public/assets/instagram.svg
  public/assets/linkedin.svg
  public/assets/logo.svg
  public/assets/logo.webp
  src/app/layout.js
  src/components/Footer.jsx
  src/data/Footer.js
Labels: ready for review

#45 debugged screen dim issues
  public/board/alejandra.webp
  public/board/andrea.webp
  public/board/emma.webp
  public/board/leanna.webp
  public/board/leila.webp
  src/app/board/page.js
  src/components/Footer.jsx
  src/components/Navigation.jsx
  src/components/board/Board.jsx
  src/components/board/BoardCard.jsx
  src/data/board.js
Labels: ready for review

#42 main header
  public/assets/mainHeader.webp
  src/app/page.js
  src/components/home/Header.jsx
Labels: ready for review, changes requested

#46 Felix/ouralumni
  public/board/five.webp
  public/board/four.webp
  public/board/one.webp
  public/board/six.webp
  public/board/three.webp
  public/board/two.webp
  src/components/board/Board.jsx
  src/components/board/OurAlumni.jsx
Labels: ready for review

#50 kaylie/resources1 , added the LeGAL rewards resources half
  public/WITL-logo.webp
  public/resources/fellowship.webp
  public/resources/groupPhoto.webp
  public/resources/networkDinner.webp
  src/app/resources/page.js
  src/components/Navigation.jsx
  src/components/resources/Resources.jsx
Labels: ready for review

#51 Created events header
  public/images/networkingdinner.webp
  src/app/events/page.js
  src/components/Navigation.jsx
  src/components/events/EventsHeader.jsx
Labels: ready for review

#53 Justin h im/mainblurb
  public/home/teamphoto1.webp
  public/home/teamphoto2.webp
  public/home/teamphoto3.webp
  src/app/page.js
  src/components/home/Blurb.jsx
  tailwind.config.js
Labels: ready for review

#52 added ourmission grid
  public/about/grouppic2.webp
  src/components/Footer.jsx
  src/components/about/OurMission.jsx
Labels: ready for review, changes requested

#49 initial-solution-to-issue-update-favicon
  src/app/favicon.ico
  src/app/witl icon.ico
Labels: ready for review

#47 cathy/sponsors2
  src/components/home/Header.jsx
Labels: ready for review, changes requested

#48 finished issue: sponsors pt. 1
  src/app/favicon.ico
  src/app/page.js
  src/components/home/Sponsors.jsx
Labels: changes requested

#43 Created Board header
  public/board/Exec_Board.webp
  src/app/board/page.js
  src/components/board/BoardHeader.jsx
Labels: changes requested

#69 added linebreaks
  src/components/home/Blurb.jsx
Labels: ready for review

#70 Changed the background color on the home page.
  src/components/home/Header.jsx
Labels: ready for review

#72 hanley/movesponsors
  src/components/home/Header.jsx
  src/components/home/Sponsors.jsx
Labels: ready for review

#74 Fixed spacing and sizing for blurb
  src/components/home/Blurb.jsx
Labels: ready for review

#76 Felix/curvetheaboutusdiv
  public/about/grouppic3.webp
  public/about/grouppic3top.webp
  public/about/grouppic4.webp
  src/components/about/AboutUsGroups.jsx
  src/components/about/about.jsx
Labels: ready for review

#75 hanley/new_setbanner
  src/components/home/Sponsors.jsx
Labels: ready for review

#78 React icons in footer
  src/components/Footer.jsx
  src/data/Footer.js
Labels: ready for review

#80 called Our Alumni component
  src/app/board/page.js
Labels: ready for review

#81 fixed font color for events page
  src/components/events/EventsHeader.jsx
Labels: ready for review

#77 fixed bottom padding as well to our mission
  src/components/about/OurMission.jsx
Labels: ready for review

#71 fixed spacing on home page
  public/home/events/UCLA.webp
  public/home/events/blueprint.webp
  public/home/events/dinner.webp
  src/app/contact/page.js
  src/components/Footer.jsx
  src/components/about/about.jsx
  src/components/board/BoardHeader.jsx
  src/components/contact/Contact.jsx
  src/components/events/EventsHeader.jsx
  src/components/home/Header.jsx
  src/components/home/SlideCard.jsx
  src/components/home/Slides.jsx
  src/data/eventslides.js
Labels: ready for review

#83 add witl inside
  src/components/about/about.jsx
Labels: ready for review, changes requested

#94 Added responsiveness to blurb
  src/components/home/Blurb.jsx
Labels: responsiveness, ready for review

#93 added event slides for home screen
  package-lock.json
  src/app/page.js
  src/components/home/SlideCard.jsx
  src/components/home/Slides.jsx
Labels: ready for review

#44 added core values design and board
  package-lock.json
  package.json
  public/about/corevalues/grow.svg
  public/about/corevalues/innovation.svg
  public/about/corevalues/integrity.svg
  public/about/corevalues/knowledge.svg
  public/about/corevalues/passion.svg
  public/about/corevalues/professionalism.svg
  public/about/corevalues/service.svg
  public/board/alejandra.webp
  public/board/andrea.webp
  public/board/emma.webp
  public/board/leanna.webp
  public/board/leila.webp
  src/app/about/page.js
  src/components/about/CoreValues.jsx
  src/components/about/Hexagon.jsx
Labels: do not merge

#97 fixed hover issues on home screen slides
  src/components/home/Slides.jsx
Labels: ready for review

#101 added slides on about page
  public/about/grouppic.webp
  public/about/grouppic1.webp
  public/about/grouppic3.webp
  public/about/grouppic3top.webp
  public/about/grouppic4.webp
  public/about/grouppict3.webp
  public/about/grouppict4.webp
  src/app/about/page.js
  src/components/about/AboutHeader.jsx
  src/components/about/AboutUsGroups.jsx
  src/components/about/CoreValues.jsx
  src/components/about/Hexagon.jsx
  src/components/home/Slides.jsx
Labels: ready for review

#103 added responsiveness for all slide components
  public/about/grouppict3.webp
  public/about/grouppicture3.webp
  src/components/about/AboutHeader.jsx
  src/components/about/AboutUsGroups.jsx
  src/components/home/SlideCard.jsx
  src/components/home/Slides.jsx
Labels: responsiveness, ready for review

#107 mobile responsiveness on resources page
  src/components/resources/Resources.jsx
Labels: ready for review

#109 about us page mobile responsiveness
  src/components/about/AboutHeader.jsx
Labels: ready for review

#110 made mobile responsive board fixed
  package-lock.json
  package.json
  src/components/board/BoardCard.jsx
  src/components/board/BoardHeader.jsx
  src/components/board/OurAlumni.jsx
Labels: ready for review

#118 added hover animation to change nav item colour to purple-100
  src/components/Navigation.jsx
Labels: ready for review

#115 footer icons mobile responsiveness
  src/components/Footer.jsx
Labels: ready for review

#116 Justin h im/ourmission
  src/components/about/OurMission.jsx
Labels: responsiveness, ready for review

#117 Changed font size and spacing for header and sponsors
  src/components/home/Header.jsx
  src/components/home/Slides.jsx
  src/components/home/Sponsors.jsx
Labels: responsiveness, ready for review

#79 Mailyn/calendar
  package-lock.json
  package.json
  src/app/events/page.js
  src/components/events/Calendar.jsx
  src/components/events/CalendarEvents.jsx
  src/components/events/CalendarTitle.jsx
  src/components/events/CustomEvent.jsx
  src/components/events/CustomToolbar.jsx
  src/components/events/EventDescription.jsx
  src/components/events/EventDescriptons.jsx
  src/components/events/EventsHeader.jsx
  src/components/events/index.css
  tailwind.config.js
Labels: ready for review

#133 made the indicator change color based on the image in the center.
  src/components/about/AboutUsGroups.jsx
  src/components/home/Slides.jsx
Labels: ready for review

#137 deleted events text
  src/components/home/Sponsors.jsx
Labels: changes requested

#134 added full responsiveness for about page
  public/about/corevalues/hexagon.svg
  public/about/corevalues/professionalism.svg
  public/about/grouppic1.webp
  public/about/grouppict4.webp
  public/about/grouppicture3.webp
  src/components/about/AboutHeader.jsx
  src/components/about/AboutUsGroups.jsx
  src/components/about/CoreValues.jsx
  src/components/about/OurMission.jsx
Labels: ready for review

#114 Hanley/newresourcesbanner
  package-lock.json
  package.json
  public/assets/banner.svg
  src/app/resources/page.js
  src/components/resources/BottomResourcesBanner.jsx
  src/components/resources/ResourcesHeader.jsx
  src/components/resources/TopResourcesBanner.jsx
Labels: ready for review

#139 added logo padding
  src/components/Navigation.jsx
Labels: ready for review

#140 Justin h im/footerhover
  src/components/Footer.jsx
Labels: ready for review

#141 fix responsiveness on home page
  src/components/home/Blurb.jsx
Labels: ready for review

#147 fixed ordering of component calling
  src/app/page.js
Labels: ready for review

#142 padding for sponsor banners
  src/components/home/Sponsors.jsx
Labels: ready for review, changes requested

#148 mobile responsiveness for header
  public/assets/logo-transparent.webp
  src/components/home/Header.jsx
Labels: ready for review

#153 White space removed above sponsors
  src/components/home/Sponsors.jsx
Labels: ready for review

#151 events header responsiveness
  src/components/events/EventsHeader.jsx
Labels: ready for review

#149 calendar mobile response
  package-lock.json
  package.json
  src/components/events/CalendarTitle.jsx
  src/components/events/CustomToolbar.jsx
  src/components/events/EventDescriptons.jsx
Labels: responsiveness, ready for review

#155 mobile responsiveness for 404 page
  src/components/NotFound.jsx
Labels: ready for review

#154 Added legal rewards header
  src/components/resources/Resources.jsx
Labels: ready for review

#157 fixed mobile responsiveness for about
  src/components/about/AboutHeader.jsx
Labels: ready for review

#150 fixed responsiveness for highlighted events
  src/components/home/SlideCard.jsx
  src/components/home/Slides.jsx
Labels: ready for review
