Repository acm-ucr/witl-website, pull requests merged in 2024-06, with the labels that each got.

#18 Font name change
  src/app/globals.css
  src/app/layout.js
  src/app/page.js
Labels: changes requested

#22 created 'our mission' component, contains title text
  src/app/about/page.js
  src/components/OurMission.jsx
Labels: ready for review, changes requested

#19 back to home button
  src/app/not-found.js
  src/components/NotFound.jsx
  src/components/not-found.jsx
  tailwind.config.js
Labels: ready for review
