Repository acm-ucr/witl-website, pull requests merged in 2024-08, with the labels that each got.

#175 Mailyn/transition board
  src/components/board/BoardCard.jsx
Labels: ready for review

#176 Mailyn/framer motion board
  src/components/board/Board.jsx
Labels: ready for review

#177 added join graphic
  public/resources/joingraphic/line1.svg
  public/resources/joingraphic/line2.svg
  public/resources/joingraphic/line3.svg
  public/resources/joingraphic/line4.svg
  public/resources/joingraphic/mobileline.svg
  src/app/resources/page.js
  src/components/about/CoreValues.jsx
  src/components/resources/JoinBox.jsx
  src/components/resources/JoinGraphic.jsx
  src/components/resources/Resources.jsx
Labels: responsiveness, ready for review

#178 Resources Legal Rewards Animations
  src/components/resources/Resources.jsx
Labels: ready for review

#179 Centered dots
  src/components/about/AboutUsGroups.jsx
Labels: responsiveness, ready for review

#181 made core value animations
  src/components/about/CoreValues.jsx
Labels: ready for review

#185 made events smaller
  src/components/board/BoardHeader.jsx
  src/components/events/EventsHeader.jsx
Labels: ready for review, changes requested

#184 added padding above header mobile
  src/components/home/Header.jsx
  src/components/home/Slides.jsx
Labels: ready for review

#186 framer motion for our mission component(s)
  src/components/about/OurMission.jsx
Labels: ready for review

#188 board page spacing
  src/components/board/Board.jsx
  src/components/board/BoardHeader.jsx
  src/components/events/EventsHeader.jsx
Labels: ready for review

#190 framer motion for blurb component(s)
  src/components/home/Blurb.jsx
  src/components/home/Header.jsx
Labels: ready for review

#192 Hanley/animatebanner2
  package-lock.json
  src/components/resources/ResourcesHeader.jsx
Labels: ready for review

#193 Animated carousel components
  src/components/home/Slides.jsx
Labels: ready for review

#187 fixed mobile animation for main header
  src/components/home/Header.jsx
Labels: ready for review

#189 framer motion for our sponsors
  src/components/home/Sponsors.jsx
Labels: ready for review, changes requested

#191 added animation for event header
  src/components/events/EventsHeader.jsx
Labels: ready for review

#200 added framer motion for board header
  src/components/board/BoardHeader.jsx
Labels: ready for review

#201 added intro animations for join graphic
  src/components/resources/JoinGraphic.jsx
Labels: ready for review

#219 fixed carousel scaling issues
  public/board/Ashley1.webp
  src/components/board/Board.jsx
  src/components/home/SlideCard.jsx
  src/components/home/Slides.jsx
Labels: ready for review

#220 fixed centering and scaling on home page header
  public/assets/headerImg.webp
  public/assets/logo-transparent.webp
  public/assets/mainHeader.webp
  public/assets/mobHeadImg.webp
  src/components/home/Header.jsx
  src/components/home/Slides.jsx
  src/components/resources/BottomResourcesBanner.jsx
  src/components/resources/TopResourcesBanner.jsx
Labels: changes requested

#225 make board animations a little faster
  src/components/board/Board.jsx
Labels: ready for review

#221 About Us slideshow fixes
  src/components/about/AboutUsGroups.jsx
Labels: ready for review

#227 Hanley/alumnifix
  public/board/ourAlumniFive.webp
  public/board/ourAlumniFour.webp
  public/board/ourAlumniOne.webp
  public/board/ourAlumniSix.webp
  public/board/ourAlumniThree.webp
  public/board/ourAlumniTwo.webp
  src/components/board/OurAlumni.jsx
Labels: ready for review

#195 Hanley/aboutframer
  src/components/about/AboutHeader.jsx
  src/components/about/AboutUsGroups.jsx
Labels: changes requested

#231 slide animation fluidity fix
  src/components/about/AboutUsGroups.jsx
Labels: ready for review

#232 fix 404 page
  src/components/NotFound.jsx
Labels: ready for review

#235 fixed resource page
  src/components/resources/JoinGraphic.jsx
  src/components/resources/Resources.jsx
  src/components/resources/ResourcesHeader.jsx
Labels: changes requested

#236 updated photo ashley
  public/board/Ashley.webp
  public/board/Ashley1.webp
  src/data/board.js
Labels: ready for review

#241 added hover animation for resources banner
  src/components/resources/BottomResourcesBanner.jsx
  src/components/resources/TopResourcesBanner.jsx
Labels: ready for review

#240 board page fix
  src/components/Footer.jsx
  src/components/board/Board.jsx
  src/components/board/BoardCard.jsx
  src/components/events/EventDescription.jsx
Labels: ready for review

#234 Fix text and image spacing
  src/components/about/OurMission.jsx
Labels: ready for review

#244 mobile calendar
  .github/workflows/nextjs.yml
  package-lock.json
  src/app/events/page.js
  src/components/events/CalendarEvents.jsx
  src/components/events/CalendarTitle.jsx
  src/components/events/CustomEvent.jsx
  src/components/events/CustomToolbar.jsx
  src/components/events/EventDescription.jsx
  src/components/events/EventDescriptions.jsx
  src/components/events/EventDescriptons.jsx
  src/components/events/Modal.jsx
Labels: ready for review

#246 fixed home page responsiveness for blurb and sponsors
  src/components/events/CustomToolbar.jsx
  src/components/home/Blurb.jsx
  src/components/home/Sponsors.jsx
Labels: responsiveness, ready for review
